# Generated by Django 5.1.1 on 2024-09-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('fantasy', 'fantasy'), ('sci-fi', 'sci-fi'), ('horror', 'horror'), ('thriller', 'thriller'), ('detective', 'detective'), ('romance', 'romance'), ('classics', 'classics'), ('philosophy', 'philosophy'), ('history', 'history'), ('religion', 'religion')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('publisher_email', models.EmailField(max_length=254, verbose_name='Enter the publisher`s email address')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Bestseller')),
            ],
        ),
    ]
